### ISSUE TITLE
[Bug]: POI deletion not reliable

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/poi_manager#11]
**What do we want to achieve?**

Issue reported by URG and confirmed by Oscar Copa:

*El botón de delete all POIs en el HMI no funciona correctamente. Se eliminan del mapa del HMI pero no del .yaml
Utilizar el Delete encima del POI sí que lo elimina del .yaml
Ha habido ocasiones que pese a eliminarlo mediante el HMI y eliminarse del yaml, al volver a cargar la localización, los POIs eliminados vuelven a estar presentes, pudiendo llamarles tanto con el POI Manager como por una secuencia. El problema desaparece al hacer ejecutar bringup.sh.*

**How do we plan to do it?**
_Notes:_ 
It can be related to the Interactive Marker components: the ROS based on and the Web based.
It can be related to poi_marker itself.

- Test the delete All from the rosservice
- Fix the delete all in case being necessary
- Implement a test script that verify the correct funcionality of the component
   - Add, Delete, Modify
- We should add this test in the Quality control 

**Acceptance Criteria**
- We will be able to delete single pois
- We will be able to delete all the pois
- We will see the deletion correctly updated in the hmi
- After deleting pois, If we reload the hmi page they will not be shown anymore

**Comment by rcartarobotnik** [comment]
The service /robot/poi_interactive_marker/delete_all_pois "data: true" when called from terminal, deletes all the POIs in map and in .yaml
 
When called from the HMI (with param: true), it is calling the callback but sending the param: False. Review the front end code(new HMI)
When deleting ALL the POIs from the map, it is not deleting them from the .yaml, and if deleting from the map it takes long waiting time before desappearing

**Comment by rcartarobotnik** [comment]
If trying to add a POI by using the service /robot/poi_interactive_marker/add_poi:
- from terminal it adds it to map and to .yaml file
- from the HMI it is giving the error "Cannot add a POI to an environment () different to active one (240930_LAB_3D)"

**Comment by rcartarobotnik** [comment]
When deleting one or more POIs through service call or from HMI, the drop down menu still shows the deleted points

**Comment by rcartarobotnik** [comment]
*Ha habido ocasiones que pese a eliminarlo mediante el HMI y eliminarse del yaml, al volver a cargar la localización, los POIs eliminados vuelven a estar presentes, pudiendo llamarles tanto con el POI Manager como por una secuencia.*

After deleting all the points through a rosservice call or HMI, the POIs list in ROS code is empty: see if it can be a problem of preempting the buffer in the frontend code.

**Comment by RomanRobotnik** [comment]
Fixed in #13
