### ISSUE TITLE
HMI not using RLC GoTo command when selecting it with the POI interactive marker

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/poi_manager#14]
**What do we want to achieve?**
To connect the GoTo commands of the Poi Interactive Marker (IM) to the right command manager / RMS action server

Currently, we can choose whether sendind the GoTo directly to the move_base action server or connect to the command_manager. Anyway, it should be connected to the RMS to follow the right pipeline.

**How do we plan to do it?**

- Add a connector the RMS Action Server or reuse the one used for the Command Manager

**Acceptance Criteria**

- Any GoTo command sent by using the IM will be received and processed by the RMS
- Any Cancel command will be received and processed by the RMS

**Comment by rcartarobotnik** [comment]
https://github.com/user-attachments/assets/e80f7a64-4c77-4916-a2fd-624c3d225da6
